language: go
go:
- 1.4.1

before_install:
  - go get github.com/tcnksm/ghr

script: make install-tar

after_success:
  - ghr --username therealbill --token $GITHUB_TOKEN --replace $(cat .version) dist/
