language: go
go:
- 1.4.1
- 1.3
- tip

before_install:
  - go get github.com/tcnksm/ghr

after_success:
  - ghr --username tcnksm-sample --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/

